@host = http://localhost:5176

GET {{host}}/weatherforecast/
Accept: application/json

###

GET {{host}}/books
Accept: application/json

###

GET {{host}}/books/1
Accept: application/json

###

POST {{host}}/books
Content-Type: application/json

{
  "title": "New book",
  "authorName": "New author"
}

###

PUT {{host}}/books/1
Content-Type: application/json

{
  "title": "A Perfect Spy",
  "authorName": "John le Carré"
}

###

DELETE {{host}}/books/1

###

GET {{host}}/authors
Accept: application/json

###
